services:
  - type: web
    name: removing-multiple-duplicate-votes
    runtime: python
    plan: free
    rootDir: Removing-Multiple-Votes-by-using-De-duplication-analysis-main
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn Deduplicate.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
